### ISSUE TITLE
[Bug] Extension not working

### ISSUE THREAD

**Issue by e-caliva** [spotify-util/ViewPlaylistsWithSong#7]
Hello, this is the only extension I have that is not working properly/ at all with my Spotify. I installed it the same way as the rest. What info can I share that could help solve this problem?

**Comment by elijaholmos** [comment]
Hi there, I believe the most probable cause is the version of Spotify that you're using. This extension is unfortunately only compatible with any version of Spotify before 1.1.59, prior to the UI rework. There should be an option for you to view Spotify information by finding the three dots (or equivalent menu opener) and choosing "About Spotify" from one of the submenus.

**Comment by e-caliva** [comment]
Ah I see, thanks for the info! Unfortunately I'm running 1.1.61 and am too lazy to rollback to an earlier version. Oh well it's no biggie. :)

**Comment by elijaholmos** [comment]
No problem! Sorry about the incompatibility issue. I nearly exclusively develop extensions for legacy Spiectify now.
