### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by MissTyne** [spotify-util/ViewPlaylistsWithSong#8]
I just tried the extension, I have searched for something like this forever, but I can't get it to work, the button just won't show up. Are you still working on it/planning on updating it to the latest Spicetify release? I read that you only develop for the Legacy Version, but maybe you changed your mind in the last year. Doesn't hurt to ask :)

Thank you @elijaholmos !

**Comment by elijaholmos** [comment]
hi @MissTyne! thank you for reaching out! I am sorry to inform you that I'm still rocking legacy Spotify and currently don't have any plans to update this extension to the latest version of Spicetify. it is possible I will switch off legacy Spotify someday, but I currently have no plans to do so.
